Profiles:
    OrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *Orderer
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Bank
                    - *Owner
                    - *Storage
                    - *Supervisor
    OrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Bank
                - *Owner
                - *Storage
                - *Supervisor

Organizations:
    - &Orderer
        Name: OrdererMSP
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/samples.cn/msp

    - &Bank
        Name: BankMSP
        ID: BankMSP
        MSPDir: crypto-config/peerOrganizations/bank.samples.cn/msp

        AnchorPeers:
          - Host: pa.bank.samples.cn
            Port: 7051

    - &Owner
        Name: OwnerMSP
        ID: OwnerMSP
        MSPDir: crypto-config/peerOrganizations/owner.samples.cn/msp

        AnchorPeers:
          - Host: zc.owner.samples.cn
            Port: 7051

    - &Storage
        Name: StorageMSP
        ID: StorageMSP
        MSPDir: crypto-config/peerOrganizations/storage.samples.cn/msp

        AnchorPeers:
          - Host: yh.storage.samples.cn
            Port: 7051

    - &Supervisor
        Name: SupervisorMSP
        ID: SupervisorMSP
        MSPDir: crypto-config/peerOrganizations/supervisor.samples.cn/msp

        AnchorPeers:
          - Host: sp.supervisor.samples.cn
            Port: 7051

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
      - orderer.samples.cn:7050
    BatchTimeout: 2s
    BatchSize:
      MaxMessageCount: 10
      AbsoluteMaxBytes: 99 MB
      PreferredMaxBytes: 512 KB

Application: &ApplicationDefaults
    Organizations:
