OrdererOrgs:
  - Name: Orderer
    Domain: samples.cn
    Specs:
      - Hostname: orderer1

PeerOrgs:
  - Name: Bank1
    Domain: bank1.samples.cn
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: Owner1
    Domain: owner1.samples.cn
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: Storage1
    Domain: storage1.samples.cn
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: Supervisor1
    Domain: supervisor1.samples.cn
    Template:
      Count: 2
    Users:
      Count: 2