OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Bank1
    Domain: bank1.example.com
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Owner1
    Domain: owner1.example.com
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Storage1
    Domain: storage1.example.com
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Supervisor1
    Domain: supervisor1.example.com
    Template:
      Count: 2
    Users:
      Count: 1